name: Playing around with workflows

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello world!"
      - name: Goodbye
        run: echo "bye!"
